version: '3.8'
services:
  db:
      image: postgres:15
      container_name: mrg-database
      restart: always
      environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
        POSTGRES_DB: mrg_lms_db
      ports:
        - '5438:5432'
      volumes:
        - db-data:/var/lib/postgresql/data

volumes:
  db-data:
  